name: Add Random Meme to Issues ğŸš€

on:
  issues:
    types:
      - opened  # âœ… ìƒˆë¡œìš´ ì´ìŠˆê°€ ìƒì„±ë  ë•Œ ì‹¤í–‰

jobs:
  add-meme:
    runs-on: ubuntu-latest
    steps:
      - name: Add a random meme to issues
        uses: jessfraz/random-meme@master
